#!/usr/bin/env python
##Falta adicionar cabeçalho
##colocar função para serviço - enable

#-----Importando bibliotecas 
import RPi.GPIO as GPIO #Lib das GPIO
import time #Lib temporizador
import os

#----Setup do GPIO, definindo interruptor
GPIO.setmode(GPIO.BCM)
GPIO.setup(3, GPIO.IN, pull_up_down=GPIO.PUD_UP)

#-----Temporizador e mensagem wall para todos 
def Shutdown(channel):
    print("Shutting Down...")
    time.sleep(5)
    os.system("sudo shutdown -h now")

#----Adicionando eventos de erros para log
GPIO.add_event_detect(3, GPIO.FALLING, callback=Shutdown, bouncetime=2000)
while 1:
    time.sleep(1)
